### ISSUE TITLE
运行提示错误from markupsafe import soft_unicode

### ISSUE THREAD

**Issue by Vincentlz** [zhuifengshen/xmind2testcase#58]
λ xmind2testcase
Traceback (most recent call last):
  File "C:\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Programs\Python\Python38\Scripts\xmind2testcase.exe\__main__.py", line 4, in <module>
  File "C:\Programs\Python\Python38\lib\site-packages\xmind2testcase\cli.py", line 8, in <module>
    from webtool.application import launch
  File "C:\Programs\Python\Python38\lib\site-packages\webtool\application.py", line 14, in <module>
    from flask import Flask, request, send_from_directory, g, render_template, abort, redirect, url_for
  File "C:\Programs\Python\Python38\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
  File "C:\Programs\Python\Python38\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Programs\Python\Python38\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Programs\Python\Python38\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Programs\Python\Python38\lib\site-packages\markupsafe\__init__.py)

**Comment by Vincentlz** [comment]
有人遇到这个错误吗，怎么解决
